### ISSUE TITLE
Crash while scrolling through "Enabled Apps"

### ISSUE THREAD

**Issue by Nick663** [Nosskirneh/NextUp-Public#30] opened 2020-03-11 08:45 UTC
The Settings-App will crash instantly after reaching the end of the "Enabled Apps" List.

**Comment by Nosskirneh** [comment] 2020-03-11 08:47
Duplicate of #29. Please update to 1.3.2~beta1 from https://henrikssonbrothers.com/cydia/repo.

**Comment by Nick663** [comment] 2020-03-11 08:52
That solved the issue. Just noticed I was on 1.3.1.

**Closed as completed** 2020-03-11 08:52 UTC

**Comment by Nosskirneh** [comment] 2020-03-11 08:54
No worries, it’s not easy to know that there’s a new beta version available. It was released one hour ago.

Anyway, let me know if any other issue arise!
